import nodemailer from 'nodemailer'
import { generatePDFBuffer } from './pdf-storage'

interface EmailData {
    to: string
    subject: string
    html: string
    from?: string
    attachments?: Array<{
        filename: string
        content: Buffer
        contentType: string
    }>
}

// Create reusable transporter object using environment variables
const createTransporter = () => {
    // Support for Gmail and other SMTP providers
    if (process.env.EMAIL_PROVIDER === 'gmail') {
        return nodemailer.createTransport({
            service: 'gmail',
            auth: {
                user: process.env.GMAIL_USER,
                pass: process.env.GMAIL_APP_PASSWORD, // Use App Password, not regular password
            },
        })
    }

    throw new Error('Email configuration not found. Please set EMAIL_PROVIDER=gmail or SMTP settings.')
}

export async function sendEmail({
    to,
    subject,
    html,
    from = process.env.EMAIL_FROM || 'GutRoot <noreply@gutroot.com>',
    attachments = []
}: EmailData): Promise<{ success: boolean; error: string | null; messageId?: string }> {
    try {
        const transporter = createTransporter()

        const mailOptions = {
            from,
            to,
            subject,
            html,
            attachments
        }

        const info = await transporter.sendMail(mailOptions)

        return {
            success: true,
            error: null,
            messageId: info.messageId
        }

    } catch (error) {
        console.error('Email service error')
        return {
            success: false,
            error: error instanceof Error ? error.message : 'Unknown email error'
        }
    }
}

export async function sendGutHealthReportWithPDF(
    email: string,
    reportData: {
        digestive_score: number
        diet_recommendations: string
        supplement_suggestions: string
        lifestyle_changes: string
        bowel_trends: string
        goal_reminders: string
        symptom_patterns_analysis: string
        ai_tip_of_week: string
        userProfile?: {
            firstName?: string
            lastName?: string
        }
    },
    userName: string = 'there'
): Promise<{ success: boolean; error: string | null; messageId?: string }> {
    try {
        const subject = `Your Personalized Gut Health Report - GutRoot`

        // Generate PDF buffer
        const { buffer: pdfBuffer, error: pdfError } = await generatePDFBuffer(reportData)

        if (pdfError || !pdfBuffer) {
            throw new Error(`Failed to generate PDF: ${pdfError}`)
        }

        // Create simple HTML email body
        const htmlContent = `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
            <h1 style="color: #0D4C47; font-size: 32px; margin-bottom: 20px;">
                🌱 Your Gut Health Report is Ready!
            </h1>
            
            <p style="font-size: 18px; line-height: 1.6; color: #2B2B2B; margin-bottom: 20px;">
                Hi ${userName},
            </p>
            
            <p style="font-size: 16px; line-height: 1.6; color: #2B2B2B; margin-bottom: 20px;">
                Thank you for completing your personalized gut health assessment! Your comprehensive report is attached as a PDF and includes:
            </p>
            
            <ul style="font-size: 16px; line-height: 1.8; color: #2B2B2B; margin-bottom: 30px;">
                <li><strong>Your Digestive Score:</strong> ${reportData.digestive_score}/10</li>
                <li><strong>Personalized Diet Recommendations</strong></li>
                <li><strong>Supplement Suggestions</strong></li>
                <li><strong>Lifestyle Changes</strong></li>
                <li><strong>Bowel Trends Analysis</strong></li>
                <li><strong>Weekly Goals & Reminders</strong></li>
                <li><strong>AI-Powered Gut Health Tip</strong></li>
            </ul>
            
            <div style="background-color: #FFE8C0; padding: 20px; border-radius: 8px; margin: 30px 0;">
                <p style="font-size: 16px; color: #2B2B2B; margin: 0; font-weight: 500;">
                    💡 <strong>This Week's Power Tip:</strong> ${reportData.ai_tip_of_week}
                </p>
            </div>
            
            <p style="font-size: 16px; line-height: 1.6; color: #2B2B2B; margin-bottom: 20px;">
                Your journey to better gut health starts today. Follow the recommendations in your report and track your progress over the coming weeks.
            </p>
            
            <div style="text-align: center; margin: 40px 0;">
                <p style="font-size: 18px; color: #0D4C47; font-weight: 600;">
                    Generated by GutRoot
                </p>
                <p style="font-size: 14px; color: #666666; margin-top: 5px;">
                    Your personalized gut health journey starts here!
                </p>
            </div>
            
            <hr style="border: none; border-top: 1px solid #e0e0e0; margin: 30px 0;">
            
            <p style="font-size: 12px; color: #888; line-height: 1.4;">
                This email was sent to ${email}. If you have any questions about your report, please contact our support team.
            </p>
        </div>
        `

        const attachments = [
            {
                filename: 'GutRoot-Health-Report.pdf',
                content: pdfBuffer,
                contentType: 'application/pdf'
            }
        ]

        return sendEmail({
            to: email,
            subject,
            html: htmlContent,
            attachments
        })

    } catch (error) {
        console.error('Error sending gut health report with PDF:', error)
        return {
            success: false,
            error: error instanceof Error ? error.message : 'Unknown error'
        }
    }
}

// Keep the original function for backward compatibility
export async function sendGutHealthReport(
    email: string,
    htmlContent: string,
    userName: string = 'there'
): Promise<{ success: boolean; error: string | null; messageId?: string }> {
    const subject = `Your Personalized Gut Health Report - GutRoot`

    return sendEmail({
        to: email,
        subject,
        html: htmlContent,
    })
} 